//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WE_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int comment_id { get; set; }
        public string comment_content { get; set; }
        public Nullable<int> account_id { get; set; }
        public Nullable<int> idea_id { get; set; }
        public Nullable<System.DateTime> comment_date { get; set; }
        public Nullable<bool> comment_status { get; set; }
    
        public virtual account account { get; set; }
        public virtual idea idea { get; set; }
    }
}
