//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WE_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class squadnerdEntities : DbContext
    {
        public squadnerdEntities()
            : base("name=squadnerdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<file> file { get; set; }
        public virtual DbSet<idea> idea { get; set; }
        public virtual DbSet<notification> notification { get; set; }
        public virtual DbSet<reaction> reaction { get; set; }
        public virtual DbSet<topic> topic { get; set; }
    }
}
