//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WE_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class topic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public topic()
        {
            this.idea = new HashSet<idea>();
        }
    
        public int topic_id { get; set; }

        [DisplayName("Topic name")]
        [Required(ErrorMessage = "Topic name is required.")]
        [MaxLength(100, ErrorMessage = "The number of characters has been exceeded, the limit is 100 characters")]
        public string topic_name { get; set; }

        [DisplayName("Description")]
        [MaxLength(200, ErrorMessage = "The number of characters has been exceeded, the limit is 200 characters")]
        public string describe { get; set; }


        [DisplayName("Closure Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> closure_date { get; set; }

        [DisplayName("Final Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> final_date { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idea> idea { get; set; }
    }
}
