//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WE_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account()
        {
            this.comment = new HashSet<comment>();
            this.idea = new HashSet<idea>();
            this.reaction = new HashSet<reaction>();
            this.notification = new HashSet<notification>();
        }
    
        public int account_id { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "Email is required.")]
        public string email { get; set; }


        [DisplayName("Confirm password")]
        [Required(ErrorMessage = "Current password is required.")]
        public string CurrentPassword { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Password is required.")]
        public string password { get; set; }

        [Required(ErrorMessage = "Confirmation Password is required.")]
        [Compare("password", ErrorMessage = "Confirm password doesn't match, Type again !")]
        [DisplayName("Confirm password")]
        public string ConfirmPassword { get; set; }


        [DisplayName("Role")]
        public Nullable<int> state { get; set; }

        [DisplayName("Role")]
        public string status {
            get { return state == 2 ? "QA Manager" : state == 3 ? "QA coordinator " : state == 4 ? "Staff": "Admin"; }
        }

        [DisplayName("Full name")]
        public string fname { get; set; }
        [DisplayName("Gender")]
        public Nullable<bool> gender { get; set; }
        [DisplayName("Gender")]
        public string _gender
        {
            get { return gender == true ? "Male" : "Female"; }
        }
        [DisplayName("Phone")]
        public Nullable<int> phone { get; set; }
        [DisplayName("Position")]
        public string position { get; set; }
        [DisplayName("Department")]
        public Nullable<int> department_id { get; set; }

        [DisplayName("Avatar")]
        public byte[] img { get; set; }
    
        public virtual department department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idea> idea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reaction> reaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notification> notification { get; set; }
    }
}
