//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WE_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public int file_id { get; set; }
        public Nullable<int> idea_id { get; set; }
        public byte[] file_name { get; set; }
    
        public virtual idea idea { get; set; }
    }
}
