//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WE_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class idea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public idea()
        {
            this.comment = new HashSet<comment>();
            this.file = new HashSet<file>();
            this.reaction = new HashSet<reaction>();
        }
    
        public int idea_id { get; set; }
        public Nullable<int> topic_id { get; set; }
        public Nullable<int> account_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string idea_content { get; set; }
        public Nullable<int> thumbs_up { get; set; }
        public Nullable<int> thumbs_down { get; set; }
        public Nullable<int> views { get; set; }
        public Nullable<System.DateTime> idea_date { get; set; }
    
        public virtual account account { get; set; }
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> file { get; set; }
        public virtual topic topic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reaction> reaction { get; set; }
    }
}
